const en = {
  Next: 'Next',
  Done: 'Done',
  'Invalid input': 'Invalid input',
  'Phone number': 'Phone number',
  'Log in': 'Log in',
  'Recover Password': 'Recover Password',
  'Recover account': 'Recover account',
  Cancel: 'Cancel',
  Yes: 'Yes',
  Proceed: 'Proceed',
  Register: 'Register',
  'Campaign could not be found': 'Campaign could not be found',
  'Campaign found': 'Campaign found. Taking you to your dashboard',
  'Error finding campaign': 'Error finding campaign',
  'Welcome back name': 'Welcome back,\n{{name}}',
  'Select campaign': 'Select campaign',
  'Please select campaign': 'Please select campaign',
  'Please enter phone number': 'Please enter phone number',
  'Invalid phone number format': 'Invalid phone number format',
  'Please enter phone number and try again': 'Please enter phone number and try again',
  'Invalid phone number': 'Invalid phone number',
  'Please enter Password': 'Please enter Password',
  'Please re-enter Password': 'Please re-enter Password',
  Password: 'Password',
  Dashboard: 'Dashboard',
  'Registration tracker': 'Registration tracker',
  Registered: 'Registered',
  Goal: 'Goal',
  Recents: 'Recents',
  'View All': 'View All',
  'Register household': 'Register household',
  'New registration': 'New registration',
  Registration: 'Registration',
  'Head of household': 'Head of household',
  'First name': 'First name',
  'Please enter first name': 'Please enter first name',
  'Middle name': 'Middle name',
  'Please enter middle name': 'Please enter middle name',
  'Middle name (optional)': 'Middle name (optional)',
  'Phone number (optional)': 'Phone number (optional)',
  Surname: 'Surname',
  'Please enter surname': 'Please enter surname',
  Sex: 'Sex',
  Age: 'Age',
  'Please enter age': 'Please enter age',
  'Age should not be below 18': 'Age should not be below 18',
  'Number of family members': 'Number of family members',
  'Please enter number of family members': 'Please enter number of family members',
  'Number should not exceed 20': 'Number should not exceed 20',
  Location: 'Location',
  Village: 'Village',
  Zone: 'Zone',
  'Village/Zone': 'Village/Zone',
  'Please select village/zone': 'Please select village/zone',
  'House number': 'House number',
  'Please enter house number': 'Please enter house number',
  'Address & Contacts': 'Address & Contacts',
  Submit: 'Submit',
  'Confirm registration': 'Confirm registration',
  DOB: 'DOB',
  Gender: 'Gender',
  'Family members': 'Family members',
  Shehia: 'Shehia',
  'Number of nets': 'Number of nets',
  'Primary phone': 'Primary phone',
  'Coupon number': 'Coupon number',
  'Resend OTP': 'Resend OTP',
  Verify: 'Verify',
  'Enter verification PIN from': 'Enter verification PIN from {{name}}',
  Verification: 'Verification',
  'Name is registered': '{{name}} is registered',
  Ok: 'Ok',
  Search: 'Search',
  Households: 'Households',
  Household: 'Household',
  Edit: 'Edit',
  Delete: 'Delete',
  'Issuance tracker': 'Issuance tracker',
  'Net issuance': 'Net issuance',
  Issued: 'Issued',
  House: 'House',
  'Enter coupon to issue net': 'Enter coupon to issue net',
  'Issue net': 'Issue net',
  'Number of net(s) to be given': 'Number of net(s) to be given',
  'Nets issued to name': '{{number}} nets issued to {{name}}',
  'Issued nets': 'Issued nets',
  Activities: 'Activities',
  'Registration Summary': 'Registration Summary',
  Approved: 'Approved',
  Pending: 'Pending',
  'All households': 'All households',
  Approve: 'Approve',
  'Review registration': 'Review registration',
  'Disapprove this household?': 'Disapprove this household?',
  Reason: 'Reason',
  'Unfinished data': 'Unfinished data',
  'Wrong data': 'Wrong data',
  'I don\'t recorgnize the household': 'I don\'t recorgnize the household',
  Disapprove: 'Disapprove',
  'Approve registrations list confirmation': 'Are you sure you want to approve these registrations?',
  'Details submitted successfully': 'Details submitted successfully',
  'Delete registration confirmation': 'You want to delete this household information?',
  District: 'District',
  Sheha: 'Sheha',
  Street: 'Street',
  'Street/Village': 'Street/Village',
  'Recover password': 'Recover password',
  'Zamep net issuance v': 'Zamep net issuance v {{version}}',
  'Enter OTP sent to your number to reset password': 'Enter OTP sent to your number to reset password',
  'Save Password': 'Save Password',
  'New Password': 'New Password',
  'Re-enter Password': 'Re-enter Password',
  'Passwords do not match': 'Passwords do not match',
  Home: 'Home',
  Net: 'Net',
  Login: 'Login',
  Settings: 'Settings',
  'Quick support': 'Quick support',
  Hide: 'Hide',
  Show: 'Show',
  'Change picture': 'Change picture',
  'Open gallery': 'Open gallery',
  'Take picture': 'Take picture',
  'Help and Support': 'Help and Support',
  'Terms and Conditions': 'Terms and Conditions',
  'Privacy Policy': 'Privacy Policy',
  English: 'English',
  Swahili: 'Swahili',
  Logout: 'Logout',
  Save: 'Save',
  Call: 'Call',
  Male: 'Male',
  Female: 'Female',
  male: 'male',
  female: 'female',
  Loading: 'Loading',
  'Invalid Username or Password': 'Invalid username or password',
  'User not enabled to login': 'User not enabled to login, please contact system admin',
  'Wrong password, try again': 'Wrong password, try again',
  'Login successful': 'Login successful',
  'Error logging in': 'Error logging in',
  'Registration created successfully': 'Registration created successfully',
  'Registration updated successfully': 'Registration updated successfully',
  'Error creating registration': 'Error creating registration',
  'Error updating registration': 'Error updating registration',
  'Registration confirmed': 'Registration confirmed',
  'Error confirming registration': 'Error confirming registration',
  'Password sent successfully': 'Password sent successfully',
  'Error sending password': 'Error sending password',
  'No records found': 'No records found',
  'Total issued nets': 'Total issued nets',
  'Registration not found': 'Registration not found',
  'Could not issue nets': 'Could not issue nets',
  'Registration deleted successfully': 'Registration deleted successfully',
  'Error deleting registration': 'Error deleting registration',
  'Could not approve registrations': 'Could not approve registrations',
  'Could not disapprove registration': 'Could not disapprove registration',
  'Nets for this household are already issued': 'Nets for this household are already issued',
  'You are not connected to internet All data are in this device': 'You are not connected to internet. All data are in this device',
  'Uploading data to server': 'Uploading data to server...',
  'Privacy Policy Paper': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vitae turpis venenatis volutpat diam posuere morbi at augue. Dictum morbi risus tortor sed ac massa. Lacus mauris morbi molestie habitant odio lorem facilisis nunc in. Massa, nunc vivamus justo ut. Tempus nibh turpis pharetra ac felis ultricies volutpat. Sit tortor lacinia volutpat vitae integer ac varius adipiscing.\n\nSollicitudin natoque cras bibendum et pretium ornare eu varius nibh. Sagittis consectetur tincidunt id est tincidunt lobortis volutpat risus sapien.\nFeugiat vitae amet volutpat lectus. Diam elementum mattis diam massa massa diam gravida condimentum nisl.\n\n\nTristique at faucibus ac bibendum at tempor pellentesque mi. Massa volutpat sed adipiscing amet porta netus malesuada magna. Gravida eu massa eu libero tempor, leo massa ut.\n\nMassa dignissim dictumst amet, varius viverra posuere purus, proin. Elementum hac semper cursus ultricies ultricies. Ultrices morbi nulla vulputate diam auctor vitae et.\n\n\nAt iaculis parturient nibh donec. Sapien aliquet eu in hac eget aliquet sed faucibus. Ornare venenatis ridiculus venenatis condimentum nibh mauris cursus. Venenatis, auctor scelerisque enim sed consequat mus.',
  'Terms & Conditions': 'Terms & Conditions',
  'Terms & Conditions Paper': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vitae turpis venenatis volutpat diam posuere morbi at augue. Dictum morbi risus tortor sed ac massa. Lacus mauris morbi molestie habitant odio lorem facilisis nunc in. Massa, nunc vivamus justo ut. Tempus nibh turpis pharetra ac felis ultricies volutpat. Sit tortor lacinia volutpat vitae integer ac varius adipiscing.\n\nSollicitudin natoque cras bibendum et pretium ornare eu varius nibh. Sagittis consectetur tincidunt id est tincidunt lobortis volutpat risus sapien.\nFeugiat vitae amet volutpat lectus. Diam elementum mattis diam massa massa diam gravida condimentum nisl.\n\n\nTristique at faucibus ac bibendum at tempor pellentesque mi. Massa volutpat sed adipiscing amet porta netus malesuada magna. Gravida eu massa eu libero tempor, leo massa ut.\n\nMassa dignissim dictumst amet, varius viverra posuere purus, proin. Elementum hac semper cursus ultricies ultricies. Ultrices morbi nulla vulputate diam auctor vitae et.\n\n\nAt iaculis parturient nibh donec. Sapien aliquet eu in hac eget aliquet sed faucibus. Ornare venenatis ridiculus venenatis condimentum nibh mauris cursus. Venenatis, auctor scelerisque enim sed consequat mus.',
};
export default en;
