const sw = {
  Next: 'Inayofuata',
  Done: 'Kamilisha',
  'Invalid input': 'Ingizo sio sahihi',
  'Phone number': 'Nambari ya simu',
  'Log in': 'Ingia',
  'Recover Password': 'Badili neno la siri',
  'Recover account': 'Badili neno la siri',
  Cancel: 'Sitisha',
  Yes: 'Ndio',
  Proceed: 'Endelea',
  Register: 'Sajili',
  'Campaign could not be found': 'Hauna kampeni hai. Wasiliana na msimamizi wa mfumo',
  'Campaign found': 'Una kampeni hai. Tunakupeleka kwenye dashibodi',
  'Error finding campaign': 'Hakuna kampeni',
  'Welcome back name': 'Karibu,\n{{name}}',
  'Select campaign': 'Chagua kampeni',
  'Please select campaign': 'Chagua kampeni',
  'Please enter phone number': 'Andika namba ya simu',
  'Invalid phone number format': 'Umekosea namba ya simu',
  'Please enter phone number and try again': 'Andika namba ya simu urudie tena',
  'Invalid phone number': 'Namba sio sahihi',
  'Please enter Password': 'Andika neno la siri',
  'Please re-enter Password': 'Andika tena neno la siri',
  Password: 'Neno la siri',
  Dashboard: 'Dashibodi',
  'Registration tracker': 'Kipima usajili',
  Registered: 'Imesajiliwa',
  Goal: 'Lengo',
  Recents: 'Za muda huu',
  'View All': 'Tizama zote',
  'Register household': 'Sajili kaya',
  'New registration': 'Usajili mpya',
  Registration: 'Usajili',
  'Head of household': 'Mkuu wa kaya',
  'First name': 'Jina la kwanza',
  'Please enter first name': 'Andika jina la kwanza',
  'Middle name': 'Jina la kati',
  'Please enter middle name': 'Andika jina la kati',
  'Middle name (optional)': 'Jina la kati (sio lazima)',
  'Phone number (optional)': 'Nambari ya simu (sio lazima)',
  Surname: 'Jina la ukoo',
  'Please enter surname': 'Andika jina la ukoo',
  Sex: 'Jinsi',
  Age: 'Umri',
  'Please enter age': 'Andika umri',
  'Age should not be below 18': 'Umri usipungue 18',
  'Number of family members': 'Idadi ya wana familia',
  'Please enter number of family members': 'Ingiza idadi ya wana familia',
  'Number should not exceed 20': 'Idadi haitakiwi kuzidi 20',
  Location: 'Mahali anapoishi',
  Village: 'Kijiji',
  Zone: 'Zone',
  'Village/Zone': 'Kijiji/Zone',
  'Please select village/zone': 'Chagua kijiji/zone',
  'House number': 'Namba ya nyumba',
  'Please enter house number': 'Ingiza namba ya nyumba',
  'Address & Contacts': 'Anuani & Mawasiliano',
  Submit: 'Wasilisha',
  'Confirm registration': 'Hakiki usajili',
  DOB: 'Tarehe ya kuzaliwa',
  Gender: 'Jinsi',
  'Family members': 'Idadi ya wanafamilia',
  Shehia: 'Shehia',
  'Number of nets': 'Idadi ya vyandarua',
  'Primary phone': 'Namba ya simu',
  'Coupon number': 'Namba ya kuponi',
  'Resend OTP': 'Tuma OTP',
  Verify: 'Hakiki',
  'Enter verification PIN from': 'Ingiza namba ya uhakiki kutoka kwa {{name}}',
  Verification: 'Uhakiki',
  'Name is registered': '{{name}} amesajiliwa',
  Ok: 'Sawa',
  Search: 'Tafuta',
  Households: 'Kaya',
  Household: 'Kaya',
  Edit: 'Sahihisha',
  Delete: 'Futa',
  'Issuance tracker': 'Kipima ugawaji',
  'Net issuance': 'Ugawaji wa vyandarua',
  Issued: 'Vilivyotolewa',
  House: 'Nyumba',
  'Enter coupon to issue net': 'Ingiza kuponi kugawa chandarua',
  'Issue net': 'Gawa chandarua',
  'Number of net(s) to be given': 'Idadi ya vyandarua vya kupewa',
  'Nets issued to name': '{{number}} {{name}} amepewa vyandarua',
  'Issued nets': 'Vyandarua vilivyotolewa',
  Activities: 'Shughuli',
  'Registration Summary': 'Mwenendo wa usajili',
  Approved: 'Imepitishwa',
  Pending: 'Inasubiri',
  'All households': 'Kaya zote',
  Approve: 'Pitisha',
  'Review registration': 'Hakiki usajili',
  'Disapprove this household?': 'kataa taarifa ya kaya?',
  Reason: 'Sababu',
  'Unfinished data': 'Taarifa haijakamilika',
  'Wrong data': 'Taarifa sio sahihi',
  'I don\'t recorgnize the household': 'Kaya siifahamu',
  Disapprove: 'Kataa',
  'Approve registrations list confirmation': 'Una uhakika kuidhinisha taarifa hizi?',
  'Details submitted successfully': 'Taarifa zimeingizwa kwa mafanikio',
  'Delete registration confirmation': 'Unataka kufuta taarifa hii ya mkuu wa kaya?',
  District: 'Wilaya',
  Sheha: 'Sheha',
  Street: 'Zone',
  'Street/Village': 'Zone/Village',
  'Recover password': 'Badili neno la siri',
  'Zamep net issuance v': 'Zamep ITN v {{version}}',
  'Enter OTP sent to your number to reset password': 'Andika OTP iliyotumwa kwenye simu yako',
  'Save Password': 'Hifadhi neno la siri',
  'New Password': 'Neno jipya la siri',
  'Re-enter Password': 'Andika tena la siri',
  'Passwords do not match': 'Neno la siri halijafanana',
  Home: 'Nyumbani',
  Net: 'Vyandarua',
  Login: 'Ingia',
  Settings: 'Mipangilio',
  'Quick support': 'Msaada wa haraka',
  Hide: 'Ficha',
  Show: 'Onesha',
  'Change picture': 'Badili picha',
  'Open gallery': 'Fungua jarada la picha',
  'Take picture': 'Piga picha',
  'Help and Support': 'Msaada',
  'Terms and Conditions': 'Vigezo na masharti',
  'Privacy Policy': 'Sera ya faragha',
  English: 'Kingereza',
  Swahili: 'Swahili',
  Logout: 'Toka nje',
  Save: 'Hifadhi',
  Call: 'Piga',
  Male: 'Kiume',
  Female: 'Kike',
  male: 'kiume',
  female: 'kike',
  Loading: 'Loading',
  'Invalid Username or Password': 'Umekosea namba ya simu au neno la siri',
  'User not enabled to login': 'Akaunti yako imezuiliwa, wasiliana na msimamizi wa mfumo',
  'Wrong password, try again': 'Umekosea neno la siri, jaribu tena',
  'Login successful': 'Umefanikiwa kuingia',
  'Error logging in': 'Changamoto ya kuingia',
  'Registration created successfully': 'Umefanikiwa kufanya usajili',
  'Registration updated successfully': 'Umefanikiwa kufanya marekebisho',
  'Error creating registration': 'Usajili umeshindikana',
  'Error updating registration': 'Marekebisho yameshindikana',
  'Registration confirmed': 'Usajili umethibitishwa',
  'Error confirming registration': 'Jaribio limeshindikana',
  'Password sent successfully': 'Neno la siri limetumwa kwenye namba yako',
  'Error sending password': 'Imeshindikana kutuma neno la siri kwenye namba yako',
  'No records found': 'Hakuna taarifa yoyote',
  'Total issued nets': 'Vyandarua vilivyotolewa',
  'Registration not found': 'Kuponi haipo',
  'Could not issue nets': 'Imeshindikana kutoa chandarua',
  'Registration deleted successfully': 'Taarifa imefutwa kikamilifu',
  'Error deleting registration': 'Jaribio limeshindikana',
  'Could not approve registrations': 'Hauwezi kuthibitisha usajili',
  'Could not disapprove registration': 'Jaribio limeshindikana',
  'Nets for this household are already issued': 'Kaya imeshachukua vyandarua vyake',
  'You are not connected to internet All data are in this device': 'Haupo kwenye mtandao. Taarifa zitapakiwa ukijiunga na mtandao',
  'Uploading data to server': 'Pakia taarifa...',
  'Privacy Policy Paper': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vitae turpis venenatis volutpat diam posuere morbi at augue. Dictum morbi risus tortor sed ac massa. Lacus mauris morbi molestie habitant odio lorem facilisis nunc in. Massa, nunc vivamus justo ut. Tempus nibh turpis pharetra ac felis ultricies volutpat. Sit tortor lacinia volutpat vitae integer ac varius adipiscing.\n\nSollicitudin natoque cras bibendum et pretium ornare eu varius nibh. Sagittis consectetur tincidunt id est tincidunt lobortis volutpat risus sapien.\nFeugiat vitae amet volutpat lectus. Diam elementum mattis diam massa massa diam gravida condimentum nisl.\n\n\nTristique at faucibus ac bibendum at tempor pellentesque mi. Massa volutpat sed adipiscing amet porta netus malesuada magna. Gravida eu massa eu libero tempor, leo massa ut.\n\nMassa dignissim dictumst amet, varius viverra posuere purus, proin. Elementum hac semper cursus ultricies ultricies. Ultrices morbi nulla vulputate diam auctor vitae et.\n\n\nAt iaculis parturient nibh donec. Sapien aliquet eu in hac eget aliquet sed faucibus. Ornare venenatis ridiculus venenatis condimentum nibh mauris cursus. Venenatis, auctor scelerisque enim sed consequat mus.',
  'Terms & Conditions': 'Terms & Conditions',
  'Terms & Conditions Paper': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vitae turpis venenatis volutpat diam posuere morbi at augue. Dictum morbi risus tortor sed ac massa. Lacus mauris morbi molestie habitant odio lorem facilisis nunc in. Massa, nunc vivamus justo ut. Tempus nibh turpis pharetra ac felis ultricies volutpat. Sit tortor lacinia volutpat vitae integer ac varius adipiscing.\n\nSollicitudin natoque cras bibendum et pretium ornare eu varius nibh. Sagittis consectetur tincidunt id est tincidunt lobortis volutpat risus sapien.\nFeugiat vitae amet volutpat lectus. Diam elementum mattis diam massa massa diam gravida condimentum nisl.\n\n\nTristique at faucibus ac bibendum at tempor pellentesque mi. Massa volutpat sed adipiscing amet porta netus malesuada magna. Gravida eu massa eu libero tempor, leo massa ut.\n\nMassa dignissim dictumst amet, varius viverra posuere purus, proin. Elementum hac semper cursus ultricies ultricies. Ultrices morbi nulla vulputate diam auctor vitae et.\n\n\nAt iaculis parturient nibh donec. Sapien aliquet eu in hac eget aliquet sed faucibus. Ornare venenatis ridiculus venenatis condimentum nibh mauris cursus. Venenatis, auctor scelerisque enim sed consequat mus.',
};
export default sw;
